blog/config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :clases
  root 'welcome#index'
end

blog/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

blog/app/models/clase.rb
class Clase < ApplicationRecord
    validates :comentario, presence: true, length: {minimum: 15}
end

blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

blog/app/controllers/clases_controller.rb
class ClasesController < ApplicationController

    def index
        @clases = Clase.all
    end

    def show
        @clase = Clase.find(params[:id])
    end

    def new
        @clase = Clase.new
    end

    def create
        @clase = Clase.new(clase_params)

        if @clase.save
            redirect_to @clase
        else
            render 'new'
        end
    end

    private
        def clase_params
            params.require(:clase).permit(:comentario)
        end

end

blog/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

blog/app/helpers/application_helper.rb
module ApplicationHelper
end

blog/app/helpers/clases_helper.rb
module ClasesHelper
end

blog/app/helpers/welcome_helper.rb
module WelcomeHelper
end

blog/app/views/clases/index.html.erb
<h1>Lista de comentarios</h1>

<table>
    <tr>
        <th>Comentarios</th>
        <th></th>
    </tr>

    <% @clases.each do |clase| %>
        <tr>
            <td><%= clase.comentario %></td>
            <td><%= link_to 'Show', clase_path(clase) %></td>
        </tr>
    <% end %>
</table>

<%= link_to 'Nuevo Comentario', new_clase_path %>

blog/app/views/clases/new.html.erb
<h1>Nuevo comentario foro</h1>

<%= form_with scope: :clase, url: clases_path, local: true do |form| %>

    <% if @clase.errors.any? %>
        <div id="error_explanation">
            <h2>
                <%= pluralize(@clase.errors.count, "error,") %>
                prohibido este comentario
            </h2>
            <ul>
                <% @clase.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <p>
        <%= form.label :comentario %><br>
        <%= form.text_area :comentario %>
    </p>

    <p>
        <%= form.submit :"Guardar comentario"%>
    </p>

<% end %>

<%= link_to 'Atras', clases_path %>

blog/app/views/clases/show.html.erb
<p>
    <strong>Comentario</strong>
    <%= @clase.comentario %>
</p>

<%= link_to 'Atras', clases_path %>

blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

blog/app/views/welcome/index.html.erb
<h1>Comunidad UNAB</h1>
<P>BIENVENIDO</P>

<%= link_to 'Comentarios', controller: 'clases' %>